/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List V2-supported assets and network capabilities */
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read exact available and reserved ledger balances */
        get: operations["listBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/ledger/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List immutable ledger transactions affecting the merchant */
        get: operations["listLedgerTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List merchant dashboard invoices */
        get: operations["listInvoices"];
        put?: never;
        /** Create an invoice */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch an invoice */
        get: operations["getInvoice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/invoices/{id}/select-payment-method": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select asset + network and finalize the invoice */
        post: operations["selectPaymentMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/invoices/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an invoice */
        post: operations["cancelInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/invoices/{id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List an invoice's payments */
        get: operations["listInvoicePayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/invoices/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read durable invoice events from a reconnect cursor */
        get: operations["listInvoiceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/invoices/{id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream durable invoice projections with SSE */
        get: operations["streamInvoiceEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payouts */
        get: operations["listPayouts"];
        put?: never;
        /** Create a payout */
        post: operations["createPayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/payouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a payout */
        get: operations["getPayout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/payouts/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a payout */
        post: operations["decidePayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/payouts/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a payout before signing */
        post: operations["cancelPayout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/public/checkouts/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a capability-bound hosted checkout */
        get: operations["getPublicCheckout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/public/checkouts/{publicId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll the customer-safe checkout status */
        get: operations["getPublicCheckoutStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/public/checkouts/{publicId}/select-payment-method": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select an allowed payment method using the checkout capability */
        post: operations["selectPublicCheckoutPaymentMethod"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/webhook-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List webhook endpoints */
        get: operations["listWebhookEndpoints"];
        put?: never;
        /** Create a webhook endpoint */
        post: operations["createWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/webhook-endpoints/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update or disable a webhook endpoint */
        patch: operations["updateWebhookEndpoint"];
        trace?: never;
    };
    "/api/v2/webhook-endpoints/{id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a webhook signing secret */
        post: operations["rotateWebhookEndpointSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/webhook-events/{id}/redeliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue redelivery of a terminal webhook event */
        post: operations["redeliverWebhookEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AssetCatalogResponse: {
            assets: {
                asset: string;
                name: string;
                decimals: number;
                network: string;
                networkName: string;
                contractAddress: string | null;
                native: boolean;
                /** @constant */
                receivingSupported: true;
                payoutSupported: boolean;
            }[];
        };
        CreateInvoiceRequest: {
            fiatAmount: string;
            currency: string;
            orderId?: string;
            metadata?: {
                [key: string]: string;
            };
            successUrl?: string;
            cancelUrl?: string;
            callbackUrl?: string;
            expiresInSeconds?: number;
        };
        BalancesResponse: {
            balances: {
                asset: string;
                network: string;
                available: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                };
                reserved: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                };
            }[];
        };
        LedgerTransactionsResponse: {
            transactions: {
                id: string;
                type: string;
                referenceType: string;
                referenceId: string;
                effectiveAt: string;
                createdAt: string;
                reversalOf: string | null;
                postings: {
                    /** @enum {string} */
                    accountPurpose: "CUSTODY_DEPOSIT" | "CUSTODY_HOT_WALLET" | "MERCHANT_AVAILABLE" | "MERCHANT_RESERVED" | "PLATFORM_FEE_REVENUE" | "NETWORK_FEE_EXPENSE" | "RECONCILIATION_SUSPENSE";
                    /** @enum {string} */
                    ownerType: "MERCHANT" | "PLATFORM";
                    asset: string;
                    amount: string;
                }[];
            }[];
            nextCursor: string | null;
        };
        SelectPaymentMethodRequest: {
            asset: string;
            network: string;
        };
        InvoiceResource: {
            id: string;
            publicId: string;
            /** @enum {string} */
            environment: "test" | "live";
            /** @enum {string} */
            status: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "OVERPAID" | "EXPIRED" | "CANCELLED" | "MANUAL_REVIEW";
            orderId: string | null;
            version: number;
            fiat: {
                amount: string;
                amountDisplay: string;
                currency: string;
                exponent: number;
            };
            asset: string | null;
            network: string | null;
            cryptoDue: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            confirmedTotal: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            unconfirmedTotal: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            destination: {
                address: string;
                network: string;
            } | null;
            quote: {
                id: string;
                quotedAt: string;
                expiresAt: string;
            } | null;
            metadata: {
                [key: string]: string;
            };
            expiresAt: string | null;
            paidAt: string | null;
            cancelledAt: string | null;
            createdAt: string;
            updatedAt: string;
        };
        InvoicePaymentsResponse: {
            payments: {
                id: string;
                chainEventId: string;
                /** @enum {string} */
                status: "OBSERVED" | "CONFIRMING" | "CONFIRMED" | "APPLIED" | "REVERSED" | "MANUAL_REVIEW";
                amount: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                };
                asset: string;
                network: string;
                txHash: string;
                observedAt: string;
                confirmedAt: string | null;
            }[];
        };
        DashboardInvoiceListQuery: {
            after?: string;
            /** @default 50 */
            limit: number;
            /** @enum {string} */
            status?: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "OVERPAID" | "EXPIRED" | "CANCELLED" | "MANUAL_REVIEW";
        };
        DashboardInvoiceList: {
            invoices: {
                id: string;
                publicId: string;
                /** @enum {string} */
                environment: "test" | "live";
                /** @enum {string} */
                status: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "OVERPAID" | "EXPIRED" | "CANCELLED" | "MANUAL_REVIEW";
                /** @enum {string} */
                customerStatus: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "EXPIRED" | "CANCELLED" | "PROCESSING";
                orderId: string | null;
                fiat: {
                    amount: string;
                    amountDisplay: string;
                    currency: string;
                    exponent: number;
                };
                asset: string | null;
                network: string | null;
                cryptoDue: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                } | null;
                confirmedTotal: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                } | null;
                unconfirmedTotal: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                } | null;
                paymentCount: number;
                expiresAt: string | null;
                paidAt: string | null;
                createdAt: string;
                updatedAt: string;
            }[];
            nextCursor: string | null;
            hasMore: boolean;
        };
        InvoiceEventQuery: {
            after?: string;
            /** @default 50 */
            limit: number;
        };
        InvoiceEventBatch: {
            events: {
                eventId: string;
                /** @enum {string} */
                type: "invoice.ready.v1" | "invoice.payment_observed.v1" | "invoice.payment_confirmed.v1" | "invoice.payment_reversed.v1" | "invoice.paid.v1" | "invoice.expired.v1" | "invoice.processing.v1";
                occurredAt: string;
                invoice: {
                    id: string;
                    publicId: string;
                    /** @enum {string} */
                    status: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "EXPIRED" | "CANCELLED" | "PROCESSING";
                    confirmedTotal: {
                        amount: string;
                        amountDisplay: string;
                        decimals: number;
                    } | null;
                    unconfirmedTotal: {
                        amount: string;
                        amountDisplay: string;
                        decimals: number;
                    } | null;
                    expiresAt: string | null;
                    paidAt: string | null;
                    updatedAt: string;
                };
                cursor: string;
            }[];
            current: {
                id: string;
                publicId: string;
                /** @enum {string} */
                status: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "EXPIRED" | "CANCELLED" | "PROCESSING";
                confirmedTotal: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                } | null;
                unconfirmedTotal: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                } | null;
                expiresAt: string | null;
                paidAt: string | null;
                updatedAt: string;
            };
            nextCursor: string | null;
            hasMore: boolean;
        };
        /** @enum {string} */
        InvoiceStatus: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "OVERPAID" | "EXPIRED" | "CANCELLED" | "MANUAL_REVIEW";
        CreatePayoutRequest: {
            asset: string;
            network: string;
            amount: string;
            destinationAddress: string;
            orderId?: string;
            metadata?: {
                [key: string]: string;
            };
        };
        ApprovePayoutRequest: {
            /** @enum {string} */
            decision: "APPROVE" | "REJECT";
            twoFactorToken: string;
            reason?: string;
        };
        CancelPayoutRequest: {
            reason: string;
        };
        PayoutResource: {
            id: string;
            /** @enum {string} */
            environment: "test" | "live";
            /** @enum {string} */
            status: "CREATED" | "APPROVAL_REQUIRED" | "APPROVED" | "REJECTED" | "CANCELLED" | "RESERVED" | "SIGNING" | "BROADCAST" | "CONFIRMING" | "COMPLETED" | "FAILED" | "MANUAL_REVIEW";
            orderId: string | null;
            asset: string;
            network: string;
            amount: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            };
            sendAmount?: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            feeAmount?: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            reservedAmount?: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            approvalsRequired?: number;
            approvalsCollected?: number;
            destinationAddress: string;
            txHash: string | null;
            failureCode?: string | null;
            createdAt: string;
            updatedAt: string;
        };
        /** @enum {string} */
        PayoutStatus: "CREATED" | "APPROVAL_REQUIRED" | "APPROVED" | "REJECTED" | "CANCELLED" | "RESERVED" | "SIGNING" | "BROADCAST" | "CONFIRMING" | "COMPLETED" | "FAILED" | "MANUAL_REVIEW";
        PayoutList: {
            payouts: components["schemas"]["PayoutResource"][];
            total: number;
        };
        PublicCheckoutSelectRequest: {
            asset: string;
            network: string;
        };
        PublicCheckoutResource: {
            publicId: string;
            /** @enum {string} */
            environment: "test" | "live";
            /** @enum {string} */
            status: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "EXPIRED" | "CANCELLED" | "PROCESSING";
            revision: string;
            fiat: {
                amount: string;
                amountDisplay: string;
                currency: string;
                exponent: number;
            };
            methods: {
                asset: string;
                assetName: string;
                iconUrl: string | null;
                network: string;
                networkName: string;
            }[];
            payment: {
                asset: string;
                assetName: string;
                network: string;
                networkName: string;
                address: string;
                paymentUri: string | null;
                amountDue: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                };
            } | null;
            confirmation: {
                /** @enum {string} */
                state: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "EXPIRED" | "CANCELLED" | "PROCESSING";
                confirmed: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                } | null;
                unconfirmed: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                } | null;
                remaining: {
                    amount: string;
                    amountDisplay: string;
                    decimals: number;
                } | null;
                isFullyConfirmed: boolean;
            };
            selectable: boolean;
            expiresAt: string | null;
            quoteExpiresAt: string | null;
            successUrl: string | null;
            cancelUrl: string | null;
            guidance: ("checkout.guidance.send_exact_amount" | "checkout.guidance.single_payment_only" | "checkout.guidance.multiple_payments_accepted" | "checkout.guidance.underpayment_tolerance" | "checkout.guidance.awaiting_confirmations" | "checkout.guidance.partial_payment_remaining" | "checkout.guidance.late_payment_warning" | "checkout.guidance.late_payment_credited" | "checkout.guidance.late_payment_manual_review" | "checkout.guidance.late_payment_refund" | "checkout.guidance.cancelled_do_not_pay" | "checkout.guidance.payment_complete" | "checkout.guidance.overpayment_received")[];
        };
        PublicCheckoutStatus: {
            publicId: string;
            /** @enum {string} */
            status: "REQUIRES_PAYMENT_METHOD" | "AWAITING_PAYMENT" | "CONFIRMING" | "PARTIALLY_PAID" | "PAID" | "EXPIRED" | "CANCELLED" | "PROCESSING";
            revision: string;
            confirmed: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            unconfirmed: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            remaining: {
                amount: string;
                amountDisplay: string;
                decimals: number;
            } | null;
            isFullyConfirmed: boolean;
            expiresAt: string | null;
        };
        CreateWebhookEndpointRequest: {
            url: string;
            events: ("invoice.ready.v1" | "invoice.payment_observed.v1" | "invoice.payment_confirmed.v1" | "invoice.payment_reversed.v1" | "invoice.paid.v1" | "invoice.overpaid.v1" | "invoice.expired.v1" | "invoice.manual_review.v1" | "invoice.receipt_unallocated.v1" | "invoice.receipt_unallocated_reversed.v1" | "invoice.receipt_unallocated_reincluded.v1" | "payout.approval_required.v1" | "payout.broadcast.v1" | "payout.cancelled.v1" | "payout.completed.v1" | "payout.failed.v1" | "payout.manual_review.v1" | "payout.security_changed.v1" | "conversion.reserved.v1" | "conversion.completed.v1" | "conversion.cancelled.v1" | "conversion.failed.v1" | "conversion.manual_review.v1")[];
        };
        UpdateWebhookEndpointRequest: {
            url?: string;
            events?: ("invoice.ready.v1" | "invoice.payment_observed.v1" | "invoice.payment_confirmed.v1" | "invoice.payment_reversed.v1" | "invoice.paid.v1" | "invoice.overpaid.v1" | "invoice.expired.v1" | "invoice.manual_review.v1" | "invoice.receipt_unallocated.v1" | "invoice.receipt_unallocated_reversed.v1" | "invoice.receipt_unallocated_reincluded.v1" | "payout.approval_required.v1" | "payout.broadcast.v1" | "payout.cancelled.v1" | "payout.completed.v1" | "payout.failed.v1" | "payout.manual_review.v1" | "payout.security_changed.v1" | "conversion.reserved.v1" | "conversion.completed.v1" | "conversion.cancelled.v1" | "conversion.failed.v1" | "conversion.manual_review.v1")[];
            /** @constant */
            active?: false;
        };
        RotateWebhookSecretRequest: {
            overlapSeconds?: number;
        };
        WebhookEndpointResource: {
            id: string;
            url: string;
            events: ("invoice.ready.v1" | "invoice.payment_observed.v1" | "invoice.payment_confirmed.v1" | "invoice.payment_reversed.v1" | "invoice.paid.v1" | "invoice.overpaid.v1" | "invoice.expired.v1" | "invoice.manual_review.v1" | "invoice.receipt_unallocated.v1" | "invoice.receipt_unallocated_reversed.v1" | "invoice.receipt_unallocated_reincluded.v1" | "payout.approval_required.v1" | "payout.broadcast.v1" | "payout.cancelled.v1" | "payout.completed.v1" | "payout.failed.v1" | "payout.manual_review.v1" | "payout.security_changed.v1" | "conversion.reserved.v1" | "conversion.completed.v1" | "conversion.cancelled.v1" | "conversion.failed.v1" | "conversion.manual_review.v1")[];
            active: boolean;
            secret?: string;
            createdAt: string;
            updatedAt: string;
        };
        WebhookEndpointList: {
            endpoints: components["schemas"]["WebhookEndpointResource"][];
        };
        WebhookRedeliveryAccepted: {
            eventId: string;
            /** @constant */
            accepted: true;
        };
        ApiError: {
            /** @enum {string} */
            code: "PEV2_VALIDATION_ERROR" | "PEV2_UNAUTHORIZED" | "PEV2_FORBIDDEN" | "PEV2_NOT_FOUND" | "PEV2_IDEMPOTENCY_CONFLICT" | "PEV2_ORDER_ID_CONFLICT" | "PEV2_QUOTE_EXPIRED" | "PEV2_INVALID_TRANSITION" | "PEV2_CROSS_ENGINE_WRITE" | "PEV2_KILL_SWITCH_ACTIVE" | "PEV2_RATE_LIMITED" | "PEV2_INTERNAL";
            message: string;
            requestId: string;
            details?: {
                path: string;
                code: string;
                message: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Supported V2 catalogue. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetCatalogResponse"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listBalances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merchant ledger balances. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesResponse"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listLedgerTransactions: {
        parameters: {
            query?: {
                before?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merchant ledger history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerTransactionsResponse"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                /** @description Opaque pagination cursor from the previous response. */
                after?: string;
                limit?: number;
                status?: components["schemas"]["InvoiceStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor-paginated invoices. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardInvoiceList"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createInvoice: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvoiceRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay of a prior create. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResource"];
                };
            };
            /** @description Invoice created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque invoice id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invoice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    selectPaymentMethod: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Opaque invoice id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectPaymentMethodRequest"];
            };
        };
        responses: {
            /** @description Finalized invoice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    cancelInvoice: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Opaque invoice id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled (or already-cancelled) invoice. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listInvoicePayments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque invoice id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invoice's payments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicePaymentsResponse"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listInvoiceEvents: {
        parameters: {
            query?: {
                /** @description Durable outbox cursor returned by the previous response. */
                after?: string;
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Opaque invoice id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event batch and authoritative state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceEventBatch"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    streamInvoiceEvents: {
        parameters: {
            query?: {
                /** @description Durable outbox cursor returned by the previous response. */
                after?: string;
                limit?: number;
            };
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                /** @description Opaque invoice id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE frames whose data is an InvoiceEventBatch. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listPayouts: {
        parameters: {
            query?: {
                status?: components["schemas"]["PayoutStatus"];
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merchant payouts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutList"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createPayout: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
                /** @description Fresh TOTP from the merchant owner; never persisted or echoed. */
                "X-Payout-2FA": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePayoutRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutResource"];
                };
            };
            /** @description Payout created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getPayout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque payout id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The payout. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    decidePayout: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
                /** @description Independent active finance reviewer; defaults to the merchant owner. */
                "X-Payout-Actor-Id"?: string;
            };
            path: {
                /** @description Opaque payout id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovePayoutRequest"];
            };
        };
        responses: {
            /** @description Updated payout. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    cancelPayout: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Opaque payout id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelPayoutRequest"];
            };
        };
        responses: {
            /** @description Cancelled payout. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getPublicCheckout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque hosted-checkout capability returned with the invoice. */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customer-safe checkout state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCheckoutResource"];
                };
            };
            /** @description The checkout capability is malformed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the checkout does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getPublicCheckoutStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque hosted-checkout capability returned with the invoice. */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Small poll-safe checkout state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCheckoutStatus"];
                };
            };
            /** @description The checkout capability is malformed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the checkout does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    selectPublicCheckoutPaymentMethod: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Opaque hosted-checkout capability returned with the invoice. */
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicCheckoutSelectRequest"];
            };
        };
        responses: {
            /** @description Finalized hosted checkout. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicCheckoutResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the checkout does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listWebhookEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merchant webhook endpoints. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointList"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the invoice does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createWebhookEndpoint: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookEndpointRequest"];
            };
        };
        responses: {
            /** @description Idempotent replay; secret omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointResource"];
                };
            };
            /** @description Endpoint created; secret included once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updateWebhookEndpoint: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Opaque webhook endpoint id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookEndpointRequest"];
            };
        };
        responses: {
            /** @description Endpoint updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    rotateWebhookEndpointSecret: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Opaque webhook endpoint id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RotateWebhookSecretRequest"];
            };
        };
        responses: {
            /** @description Secret rotated; omitted on idempotent replay. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointResource"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    redeliverWebhookEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description Merchant-supplied deduplication token. Reusing a key with a different request body returns 409. */
                "Idempotency-Key": string;
            };
            path: {
                /** @description Stable webhook event id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Idempotent replay. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookRedeliveryAccepted"];
                };
            };
            /** @description Redelivery accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookRedeliveryAccepted"];
                };
            };
            /** @description The request failed validation. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Authentication is required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description V2 is not enabled, or the resource does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Idempotency, order-id, or invoice-state conflict. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Rate limited. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Internal error. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Temporarily unavailable (kill switch or unwired dependency). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
